# Use Node official image
#FROM node:18-alpine

# Set work directory
#WORKDIR /app

# Copy package files
#COPY package*.json ./

# Install dependencies
RUN #npm install

# Copy the rest of the source code
#COPY . .

# Expose server port
#EXPOSE 3000

# Start the application
#CMD ["node", "initDatabase.js"]

